server:
  port: 8080
datasource:
  driverName: mysql
  hostname: 127.0.0.1
  port: 3306
  database: sgamer
  username: root
  password: root
  charset: utf8
emailCode:
  smtpPassword: "jyrtygevbqqmccbe"
  email: "1649801526@qq.com"
